export interface Arsip {
  id: string;
  kodeKlasifikasi: string;
  nomorSurat: string;
  judul: string;
  jenisNaskah: string;
  klasifikasiKeamanan: "SR" | "R" | "T" | "B";
  tahun: number;
  tanggalSurat: string;
  deskripsi: string;
  retensiAktif: number;
  retensiInaktif: number;
  keteranganRetensi: "Musnah" | "Permanen";
  statusArsip: "Aktif" | "Inaktif";
  linkCloud: string;
  tanggalRegistrasi: string;
  registeredBy: string;
}

// Kode Klasifikasi Arsip sesuai Perwako Sungai Penuh No 49/2022
export const KODE_KLASIFIKASI = [
  // UMUM - 000
  { kode: "000", nama: "UMUM" },
  { kode: "000.1", nama: "KETATAUSAHAAN DAN KERUMAHTANGGAAN" },
  { kode: "000.1.1", nama: "Telekomunikasi" },
  { kode: "000.1.2", nama: "Perjalanan Dinas Dalam Negeri" },
  { kode: "000.1.3", nama: "Perjalanan Dinas Luar Negeri" },
  { kode: "000.1.4", nama: "Penggunaan Fasilitas Kantor" },
  { kode: "000.1.5", nama: "Rapat pimpinan" },
  { kode: "000.1.6", nama: "Penyediaan Konsumsi" },
  { kode: "000.1.7", nama: "Pengurusan Kendaraan Dinas" },
  { kode: "000.1.8", nama: "Pemeliharaan Gedung, Taman dan Peralatan Kantor" },
  { kode: "000.1.9", nama: "Pengelolaan Jaringan Listrik, Air, Telepon dan Komputer" },
  { kode: "000.1.10", nama: "Ketertiban dan Keamanan" },
  { kode: "000.1.11", nama: "Administrasi Pengelolaan Parkir" },
  { kode: "000.1.12", nama: "Administrasi Pakaian Dinas Pegawai" },
  { kode: "000.2", nama: "PERLENGKAPAN" },
  { kode: "000.2.1", nama: "Inventarisasi dan Penyimpanan" },
  { kode: "000.2.2", nama: "Pemeliharaan peralatan kantor" },
  { kode: "000.2.3", nama: "Distribusi" },
  { kode: "000.2.4", nama: "Penghapusan Barang Milik Daerah" },
  { kode: "000.2.5", nama: "Pengelolaan Database Barang Milik Daerah" },
  { kode: "000.3", nama: "PENGADAAN" },
  { kode: "000.3.1", nama: "Rencana Pengadaan Barang dan Jasa" },
  { kode: "000.3.2", nama: "Pengadaan Langsung" },
  { kode: "000.3.3", nama: "Pengadaan Tidak Langsung/Lelang" },
  { kode: "000.3.4", nama: "Swakelola" },
  { kode: "000.3.5", nama: "Pengolahan Sistem Informasi Pengadaan" },
  { kode: "000.3.6", nama: "Monitoring dan Evaluasi" },
  { kode: "000.4", nama: "PERPUSTAKAAN" },
  { kode: "000.4.1", nama: "Kebijakan di bidang Perpustakaan" },
  { kode: "000.4.2", nama: "Deposit Bahan Pustaka" },
  { kode: "000.4.3", nama: "Koleksi Pustaka" },
  { kode: "000.4.4", nama: "Pengolahan Bahan Pustaka" },
  { kode: "000.4.5", nama: "Pangkalan Data Katalog Koleksi" },
  { kode: "000.4.6", nama: "Layanan Perpustakaan" },
  { kode: "000.4.7", nama: "Kerjasama Perpustakaan" },
  { kode: "000.4.8", nama: "Pengembangan Implementasi Teknologi Informasi Perpustakaan" },
  { kode: "000.4.9", nama: "Pangkalan Data Layanan Perpustakaan" },
  { kode: "000.4.10", nama: "Konservasi" },
  { kode: "000.4.11", nama: "Reprografi" },
  { kode: "000.4.12", nama: "Transformasi Digital" },
  { kode: "000.4.13", nama: "Kurasi Digital" },
  { kode: "000.4.14", nama: "Pengembangan Perpustakaan" },
  { kode: "000.5", nama: "KEARSIPAN" },
  { kode: "000.5.1", nama: "Kebijakan di Bidang Kearsipan" },
  { kode: "000.5.2", nama: "Pembinaan Kearsipan" },
  { kode: "000.5.3", nama: "Pengelolaan Arsip Dinamis" },
  { kode: "000.5.4", nama: "Program Arsip Vital" },
  { kode: "000.5.5", nama: "Pengelolaan Arsip Terjaga" },
  { kode: "000.5.6", nama: "Penyusutan Arsip" },
  { kode: "000.5.7", nama: "Alih Media Arsip" },
  { kode: "000.5.8", nama: "Database Pengelolaan Arsip Dinamis" },
  { kode: "000.5.9", nama: "Pengelolaan Arsip Statis" },
  { kode: "000.5.10", nama: "Jasa Kearsipan" },
  { kode: "000.5.11", nama: "Pengelolaan SIKN dan JIKN" },
  { kode: "000.5.12", nama: "Pelindungan dan Penyelamatan Arsip" },
  { kode: "000.5.13", nama: "Penyelamatan Arsip Perangkat Daerah" },
  { kode: "000.5.14", nama: "Penerbitan Izin Penggunaan Arsip Tertutup" },
  { kode: "000.5.15", nama: "Pengawasan Kearsipan" },
  { kode: "000.6", nama: "PERSANDIAN" },
  { kode: "000.6.1", nama: "Kebijakan di bidang Persandian" },
  { kode: "000.6.2", nama: "Pengamanan persandian" },
  { kode: "000.6.3", nama: "Pengkajian persandian" },
  { kode: "000.6.4", nama: "Pembinaan dan Pengendalian Persandian" },
  { kode: "000.6.5", nama: "Layanan Sertifikasi Elektronik" },
  { kode: "000.7", nama: "PERENCANAAN PEMBANGUNAN" },
  { kode: "000.7.1", nama: "Musyawarah Perencanaan Pembangunan/Musrenbang" },
  { kode: "000.7.2", nama: "Perencanaan Pembangungan Daerah" },
  { kode: "000.7.3", nama: "Koordinasi dan Sinkronisasi Perencanaan Pembangunan" },
  { kode: "000.7.4", nama: "Konsultasi Perencanaan Pembangunan" },
  { kode: "000.7.5", nama: "Pemantauan, Evaluasi, Penilaian, dan Pelaporan" },
  { kode: "000.7.6", nama: "Aksi Strategis Daerah" },
  { kode: "000.7.7", nama: "Perencanaan Pendanaan Pembangunan" },
  { kode: "000.8", nama: "ORGANISASI DAN TATA LAKSANA" },
  { kode: "000.8.1", nama: "Struktur Organisasi Pemerintahan Daerah" },
  { kode: "000.8.2", nama: "Uraian Jabatan dan Tata Kerja" },
  { kode: "000.8.3", nama: "Ketatalaksanaan" },
  { kode: "000.8.4", nama: "Standar Kompetensi Jabatan" },
  { kode: "000.8.5", nama: "Evaluasi Kelembagaan" },
  { kode: "000.8.6", nama: "Koordinasi Penguatan Reformasi dan Birokrasi" },
  { kode: "000.9", nama: "PENELITIAN, PENGKAJIAN, DAN PENGEMBANGAN" },


  // PEMERINTAHAN - 100
  { kode: "100", nama: "PEMERINTAHAN" },
  { kode: "100.1", nama: "OTONOMI DAERAH" },
  { kode: "100.1.1", nama: "Kebijakan di bidang Otonomi Daerah" },
  { kode: "100.1.2", nama: "Penyelenggaraan Pemerintah Daerah" },
  { kode: "100.1.3", nama: "Penataan Daerah dan Otonomi Khusus" },
  { kode: "100.1.4", nama: "Pemilihan Kepala Daerah dan DPRD" },
  { kode: "100.1.5", nama: "Peningkatan Kapasitas Dan Evaluasi Kinerja Daerah" },
  { kode: "100.1.6", nama: "LKPJ/LKPJAMJ dan LPPD" },
  { kode: "100.2", nama: "PEMERINTAHAN UMUM" },
  { kode: "100.2.1", nama: "Kebijakan di bidang Pemerintahan Umum" },
  { kode: "100.2.2", nama: "Dekonsentrasi dan Kerjasama" },
  { kode: "100.2.3", nama: "Wilayah Administrasi dan Perbatasan" },
  { kode: "100.3", nama: "HUKUM" },
  { kode: "100.3.1", nama: "Program Legislasi" },
  { kode: "100.3.2", nama: "Rancangan Peraturan Perundang-Undangan" },
  { kode: "100.3.3", nama: "Keputusan/Ketetapan Pimpinan Pemerintah" },
  { kode: "100.3.4", nama: "Instruksi/Surat Edaran" },
  { kode: "100.3.5", nama: "Surat Perintah" },
  { kode: "100.3.6", nama: "Standar/Pedoman/Prosedur Kerja/Petunjuk Pelaksanaan" },
  { kode: "100.3.7", nama: "Nota Kesepakatan/MoU/Kontrak/Perjanjian Kerja Sama" },
  { kode: "100.3.8", nama: "Dokumentasi Hukum" },
  { kode: "100.3.9", nama: "Sosialisasi/Penyuluhan/Pembinaan Hukum" },
  { kode: "100.3.10", nama: "Bantuan/Konsultasi Hukum/Advokasi" },
  { kode: "100.3.11", nama: "Kasus/Sengketa Hukum" },
  { kode: "100.3.12", nama: "Perijinan" },
  { kode: "100.3.13", nama: "Hak atas Kekayaan Intelektual (HaKI)" },
  { kode: "100.3.14", nama: "Permohonan HaKI yang ditolak" },

  // POLITIK - 200
  { kode: "200", nama: "POLITIK" },
  { kode: "200.1", nama: "KESATUAN BANGSA DAN POLITIK" },
  { kode: "200.1.1", nama: "Kebijakan di bidang Kesatuan Bangsa dan Politik" },
  { kode: "200.1.2", nama: "Bina Ideologi dan Wawasan Kebangsaan" },
  { kode: "200.1.3", nama: "Kewaspadaan Nasional" },
  { kode: "200.1.4", nama: "Seni, Budaya, Adat, Agama, dan Kemasyarakatan" },
  { kode: "200.1.5", nama: "Politik Dalam Negeri" },
  { kode: "200.1.6", nama: "Ketahanan Ekonomi" },
  { kode: "200.2", nama: "PEMILU" },
  { kode: "200.2.1", nama: "Kebijakan di bidang Pemilu" },
  { kode: "200.2.2", nama: "Pemutakhiran dan Penyusunan Daftar Pemilih" },
  { kode: "200.2.3", nama: "Pendaftaran dan Verifikasi Peserta Pemilu" },
  { kode: "200.2.4", nama: "Penetapan Peserta Pemilu" },
  { kode: "200.2.5", nama: "Pencalonan Pemilu" },
  { kode: "200.2.6", nama: "Kampanye Pemilu" },
  { kode: "200.2.7", nama: "Dana Kampanye" },
  { kode: "200.2.8", nama: "Pemungutan dan Penghitungan Suara" },
  { kode: "200.2.9", nama: "Penetapan Hasil Pemilu" },
  { kode: "200.2.10", nama: "Perselisihan Hasil Pemilu" },
  { kode: "200.2.11", nama: "Laporan hasil penyelenggaraan Pemilu" },

  // KEAMANAN DAN KETERTIBAN - 300
  { kode: "300", nama: "KEAMANAN DAN KETERTIBAN" },
  { kode: "300.1", nama: "SATUAN POLISI PAMONG PRAJA" },
  { kode: "300.1.1", nama: "Kebijakan di bidang Polisi Pamong Praja" },
  { kode: "300.1.2", nama: "Tata Operasional dan Prasarana Sarana" },
  { kode: "300.1.3", nama: "Peningkatan Kapasitas SDM" },
  { kode: "300.1.4", nama: "Perlindungan Masyarakat" },
  { kode: "300.1.5", nama: "Penyidik Pegawai Negeri Sipil" },
  { kode: "300.1.6", nama: "Perlindungan Hak-Hak Sipil dan Hak Asasi Manusia" },
  { kode: "300.2", nama: "PENANGGULANGAN BENCANA, PENCARIAN, DAN PERTOLONGAN" },
  { kode: "300.2.1", nama: "Kebijakan di bidang Penanggulangan Bencana" },
  { kode: "300.2.2", nama: "Perencanaan Penanggulangan Bencana, Pencarian, dan Pertolongan" },
  { kode: "300.2.3", nama: "Pencegahan dan Kesiapsiagaan" },
  { kode: "300.2.4", nama: "Potensi Pencarian dan Pertolongan" },
  { kode: "300.2.5", nama: "Bina Ketenagaan dan Pemasyarakatan" },
  { kode: "300.2.6", nama: "Operasi Pencarian dan Pertolongan" },
  { kode: "300.2.7", nama: "Rencana Pengembangan dan Standardisasi Komunikasi" },
  { kode: "300.2.8", nama: "Operasi Komunikasi" },
  { kode: "300.2.9", nama: "Inventarisasi dan Pemeliharaan" },
  { kode: "300.2.10", nama: "Pengembangan Sistem Informasi" },
  { kode: "300.2.11", nama: "Penyajian dan Layanan Informasi" },
  { kode: "300.2.12", nama: "Pelaporan dan Evaluasi" },


  // KESEJAHTERAAN RAKYAT - 400
  { kode: "400", nama: "KESEJAHTERAAN RAKYAT" },
  { kode: "400.1", nama: "PEMBANGUNAN DAERAH TERTINGGAL" },
  { kode: "400.1.1", nama: "Kebijakan Pembangunan Daerah Tertinggal" },
  { kode: "400.1.2", nama: "Pembangunan Sumber Daya" },
  { kode: "400.1.3", nama: "Peningkatan Infrastruktur" },
  { kode: "400.1.4", nama: "Pembinaan Ekonomi dan Dunia Usaha" },
  { kode: "400.1.5", nama: "Pembinaan Lembaga Sosial dan Budaya" },
  { kode: "400.1.6", nama: "Pengembangan Daerah Khusus" },
  { kode: "400.2", nama: "PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK" },
  { kode: "400.2.1", nama: "Kebijakan Pemberdayaan Perempuan dan Perlindungan Anak" },
  { kode: "400.2.2", nama: "Pengarusutamaan Gender Ekonomi, Politik Sosial dan Hukum" },
  { kode: "400.2.3", nama: "Perlindungan Perempuan" },
  { kode: "400.2.4", nama: "Perlindungan Anak" },
  { kode: "400.2.5", nama: "Tumbuh Kembang Anak" },
  { kode: "400.2.6", nama: "Penghargaan terkait gender" },
  { kode: "400.2.7", nama: "Penghargaan Kabupaten Layak Anak" },
  { kode: "400.2.8", nama: "Penghargaan Desa Ramah Perempuan Peduli Anak" },
  { kode: "400.3", nama: "PENDIDIKAN" },
  { kode: "400.3.1", nama: "Kebijakan di bidang Pendidikan" },
  { kode: "400.3.2", nama: "Pendidikan Anak Usia Dini (PAUD)" },
  { kode: "400.3.3", nama: "Pendidikan Masyarakat" },
  { kode: "400.3.4", nama: "Kursus/Pelatihan Pendidik dan Tenaga Pendidik" },
  { kode: "400.3.5", nama: "Pendidikan Dasar dan Menengah Pertama" },
  { kode: "400.3.6", nama: "Pendidikan Khusus/Layanan Khusus" },
  { kode: "400.3.7", nama: "Pembinaan Pendidik dan Tenaga Pendidik" },
  { kode: "400.3.8", nama: "Sekolah Menengah Atas" },
  { kode: "400.3.9", nama: "Pendidikan Khusus-Layanan Khusus" },
  { kode: "400.3.10", nama: "Pendidik dan Tenaga Pendidik SMA/K" },
  { kode: "400.3.11", nama: "Penilaian Pendidikan" },
  { kode: "400.3.12", nama: "Data dan Statistik Pendidikan" },
  { kode: "400.3.13", nama: "Prasarana dan Sarana Pendidikan" },
  { kode: "400.4", nama: "KEOLAHRAGAAN" },
  { kode: "400.5", nama: "KEPEMUDAAN" },
  { kode: "400.6", nama: "KEBUDAYAAN" },
  { kode: "400.7", nama: "KESEHATAN" },
  { kode: "400.8", nama: "AGAMA DAN KEPERCAYAAN" },
  { kode: "400.9", nama: "SOSIAL" },
  { kode: "400.10", nama: "PEMBERDAYAAN MASYARAKAT DESA" },
  { kode: "400.11", nama: "PERTAMANAN DAN PEMAKAMAN" },
  { kode: "400.12", nama: "KEPENDUDUKAN DAN CATATAN SIPIL" },
  { kode: "400.13", nama: "KELUARGA BERENCANA" },
  { kode: "400.14", nama: "HUBUNGAN MASYARAKAT" },

  // PEREKONOMIAN - 500
  { kode: "500", nama: "PEREKONOMIAN" },
  { kode: "500.1", nama: "KETAHANAN PANGAN" },
  { kode: "500.2", nama: "PERDAGANGAN" },
  { kode: "500.3", nama: "KOPERASI DAN USAHA KECIL MENENGAH" },
  { kode: "500.4", nama: "KEHUTANAN" },
  { kode: "500.5", nama: "KELAUTAN DAN PERIKANAN" },
  { kode: "500.6", nama: "PERTANIAN" },
  { kode: "500.7", nama: "PETERNAKAN" },
  { kode: "500.8", nama: "PERKEBUNAN" },
  { kode: "500.9", nama: "PERINDUSTRIAN" },
  { kode: "500.10", nama: "ENERGI DAN SUMBER DAYA MINERAL" },
  { kode: "500.11", nama: "PERHUBUNGAN" },
  { kode: "500.12", nama: "KOMUNIKASI DAN INFORMATIKA" },
  { kode: "500.13", nama: "PARIWISATA DAN EKONOMI KREATIF" },
  { kode: "500.14", nama: "STATISTIK" },
  { kode: "500.15", nama: "KETENAGAKERJAAN" },
  { kode: "500.16", nama: "PENANAMAN MODAL" },
  { kode: "500.17", nama: "PERTANAHAN" },
  { kode: "500.18", nama: "TRANSMIGRASI" },


  // PEKERJAAN UMUM DAN KETENAGAAN UMUM - 600
  { kode: "600", nama: "PEKERJAAN UMUM DAN KETENAGAAN UMUM" },
  { kode: "600.1", nama: "PEKERJAAN UMUM" },
  { kode: "600.1.1", nama: "Kebijakan di bidang Pekerjaan Umum" },
  { kode: "600.1.2", nama: "Penatagunaan Sumber Daya Air" },
  { kode: "600.1.3", nama: "Pengembangan Jaringan Sumber Daya Air" },
  { kode: "600.1.4", nama: "Pengelolaan Sumber Daya Air" },
  { kode: "600.1.5", nama: "Operasi dan Pemeliharaan Sumber Daya Air" },
  { kode: "600.1.6", nama: "Pengendalian Lumpur Sidoarjo" },
  { kode: "600.1.7", nama: "Pengembangan Jaringan Jalan" },
  { kode: "600.1.8", nama: "Pembangunan Jalan" },
  { kode: "600.1.9", nama: "Preservasi Jalan" },
  { kode: "600.1.10", nama: "Pengelolaan Jembatan" },
  { kode: "600.1.11", nama: "Pengelolaan Jalan Bebas Hambatan, Perkotaan, dan Daerah" },
  { kode: "600.1.12", nama: "Pengaturan Jalan Tol" },
  { kode: "600.1.13", nama: "Keterpaduan Infrastruktur Permukiman" },
  { kode: "600.1.14", nama: "Pengembangan Kawasan Permukiman" },
  { kode: "600.1.15", nama: "Pembinaan Penataan Bangunan" },
  { kode: "600.1.16", nama: "Pengembangan Sistem Penyediaan Air Minum" },
  { kode: "600.1.17", nama: "Pengembangan Penyehatan Lingkungan Permukiman" },
  { kode: "600.1.18", nama: "Pemantauan dan Evaluasi" },
  { kode: "600.2", nama: "PERUMAHAN RAKYAT DAN KAWASAN PEMUKIMAN" },
  { kode: "600.2.1", nama: "Kebijakan di bidang Perumahan Rakyat dan Kawasan Pemukiman" },
  { kode: "600.2.2", nama: "Perencanaan Pembiayaan Perumahan" },
  { kode: "600.2.3", nama: "Pola Pembiayaan Perumahan" },
  { kode: "600.2.4", nama: "Pendayagunaan Sumber Pembiayaan Perumahan" },
  { kode: "600.2.5", nama: "Perencanaan Penyediaan Perumahan" },
  { kode: "600.2.6", nama: "Penyediaan Rumah Susun" },
  { kode: "600.2.7", nama: "Penyediaan Rumah Khusus" },
  { kode: "600.2.8", nama: "Penyediaan Rumah Umum dan Komersial" },
  { kode: "600.2.9", nama: "Investasi Infrastruktur" },
  { kode: "600.2.10", nama: "Penyelenggaraan Jasa Konstruksi" },
  { kode: "600.2.11", nama: "Kelembagaan dan Sumber Daya Konstruksi" },
  { kode: "600.2.12", nama: "Kompetensi dan Produktivitas Konstruksi" },
  { kode: "600.2.13", nama: "Peningkatan Kerjasama dan Pemberdayaan Jasa Konstruksi" },
  { kode: "600.2.14", nama: "Peningkatan Jasa Konstruksi" },
  { kode: "600.2.15", nama: "Penerapan Teknologi Konstruksi" },
  { kode: "600.2.16", nama: "Rencana Pengembangan Infrastruktur PUPR" },
  { kode: "600.2.17", nama: "Pengembangan Kawasan Strategis" },
  { kode: "600.2.18", nama: "Pengembangan Kawasan Perkotaan" },
  { kode: "600.2.19", nama: "Pemantauan dan Evaluasi" },
  { kode: "600.3", nama: "TATA RUANG (TATA KOTA)" },
  { kode: "600.3.1", nama: "Kebijakan di bidang Tata Ruang" },
  { kode: "600.3.2", nama: "Perencanaan" },
  { kode: "600.3.3", nama: "Pemanfaatan dan Pengendalian" },
  { kode: "600.3.4", nama: "Pemetaan" },
  { kode: "600.4", nama: "LINGKUNGAN HIDUP" },
  { kode: "600.4.1", nama: "Kebijakan di bidang Lingkungan Hidup" },
  { kode: "600.4.2", nama: "Perencanaan Pemanfaatan SDA dan Lingkungan Hidup" },
  { kode: "600.4.3", nama: "Penerapan Kebijakan Wilayah dan Sektor" },
  { kode: "600.4.4", nama: "Ekonomi Lingkungan" },
  { kode: "600.4.5", nama: "Dampak Lingkungan" },
  { kode: "600.4.6", nama: "Pemantauan dan Pengawasan" },
  { kode: "600.4.7", nama: "Evaluasi dan Pengembangan" },
  { kode: "600.4.8", nama: "Keanekaragaman Hayati dan pengendalian Kerusakan Lahan" },
  { kode: "600.4.9", nama: "Kerusakan Ekosistem Perairan Darat" },
  { kode: "600.4.10", nama: "Mitigasi dan Rawa pelestarian Fungsi Atmosfer" },
  { kode: "600.4.11", nama: "Adaptasi Perubahan Iklim" },
  { kode: "600.4.12", nama: "Pengelolaan Bahan Berbahaya dan Beracun" },
  { kode: "600.4.13", nama: "Verifikasi Pengelolaan Limbah B3" },
  { kode: "600.4.14", nama: "Pengelolaan Limbah B3 dan Pemulihan Kontaminasi" },
  { kode: "600.4.15", nama: "Pengelolaan Sampah" },
  { kode: "600.4.16", nama: "Hukum Administrasi Lingkungan" },
  { kode: "600.4.17", nama: "Penyelesaian Sengketa Lingkungan" },
  { kode: "600.4.18", nama: "Penegakan hukum pidana lingkungan" },
  { kode: "600.4.19", nama: "Komunikasi Lingkungan" },
  { kode: "600.4.20", nama: "Penguatan Inisiatif Masyarakat" },
  { kode: "600.4.21", nama: "Peningkatan Peran Masyarakat" },
  { kode: "600.4.22", nama: "Peningkatan Peran Organisasi Kemasyarakatan" },
  { kode: "600.4.23", nama: "Data dan Informasi Lingkungan" },
  { kode: "600.4.24", nama: "Kelembagaan Lingkungan" },
  { kode: "600.4.25", nama: "Standarisasi dan teknologi" },
  { kode: "600.4.26", nama: "Pusat Sarana Pengendalian Dampak Lingkungan" },

  // PENGAWASAN - 700
  { kode: "700", nama: "PENGAWASAN" },
  { kode: "700.1", nama: "PENGAWASAN INTERNAL" },
  { kode: "700.1.1", nama: "Rencana Pengawasan" },
  { kode: "700.1.2", nama: "Pelaksanaan Pengawasan" },

  // KEPEGAWAIAN - 800
  { kode: "800", nama: "KEPEGAWAIAN" },
  { kode: "800.1", nama: "SUMBER DAYA MANUSIA" },
  { kode: "800.1.1", nama: "Penyusunan dan Penetapan Kebutuhan ASN" },
  { kode: "800.1.2", nama: "Formasi dan Pengadaan Pegawai" },
  { kode: "800.1.3", nama: "Mutasi Pegawai" },
  { kode: "800.1.4", nama: "Pengembangan Karir" },
  { kode: "800.1.5", nama: "Kinerja Aparatur Sipil Negara" },
  { kode: "800.1.6", nama: "Kode Etik, Disiplin, Pemberhentian dan Pensiun ASN" },
  { kode: "800.1.7", nama: "Bantuan Hukum" },
  { kode: "800.1.8", nama: "Status dan Kedudukan Pegawai" },
  { kode: "800.1.9", nama: "Sistem Informasi Kepegawaian" },
  { kode: "800.1.10", nama: "Pengawasan dan pengendalian" },
  { kode: "800.1.11", nama: "Administrasi Pegawai" },
  { kode: "800.1.12", nama: "Kesejahteraan Pegawai" },
  { kode: "800.1.13", nama: "Administrasi Perseorangan" },
  { kode: "800.1.14", nama: "Penilaian Kompetensi" },
  { kode: "800.2", nama: "PENDIDIKAN DAN PELATIHAN" },
  { kode: "800.2.1", nama: "Kebijakan di bidang Pendidikan dan Pelatihan" },
  { kode: "800.2.2", nama: "Pendidikan dan Pelatihan" },
  { kode: "800.2.3", nama: "Widyaiswara" },
  { kode: "800.2.4", nama: "Penyelenggaraan Diklat" },
  { kode: "800.2.5", nama: "Alumni" },

  // KEUANGAN - 900
  { kode: "900", nama: "KEUANGAN" },
  { kode: "900.1", nama: "KEUANGAN DAERAH" },
  { kode: "900.1.1", nama: "Rencana APBD dan APBD-P" },
  { kode: "900.1.2", nama: "Penyusunan Anggaran" },
  { kode: "900.1.3", nama: "Pelaksanaan Anggaran" },
  { kode: "900.1.4", nama: "Pinjaman/Hibah Luar Negeri" },
  { kode: "900.1.5", nama: "Pengelolaan APBD/Dana Pinjaman/Hibah Luar Negeri (PHLN)" },
  { kode: "900.1.6", nama: "Sistem Akuntansi Keuangan Daerah (SAKD)" },
  { kode: "900.1.7", nama: "Penyaluran Anggaran Tugas Pembantuan" },
  { kode: "900.1.8", nama: "Penerimaan Anggaran Tugas Pembantuan" },
  { kode: "900.1.9", nama: "Penyusunan Anggaran Pilkada dan Bantuan Pemilu" },
  { kode: "900.1.10", nama: "Pelaksanaan Anggaran PILKADA dan Biaya Bantuan Pemilu" },
  { kode: "900.1.11", nama: "Pemeriksaan/Pengawasan Keuangan Daerah" },
  { kode: "900.1.12", nama: "Anggaran Daerah" },
  { kode: "900.1.13", nama: "Pendapatan dan Investasi Daerah" },
  { kode: "900.1.14", nama: "Fasilitasi Dana Perimbangan" },
  { kode: "900.1.15", nama: "Pelaksanaan Dan Pertanggungjawaban Keuangan Daerah" },
] as const;


// Jenis Naskah Dinas sesuai Perwako 31/2023
export const JENIS_NASKAH = [
  { value: "Surat Masuk", label: "Surat Masuk" },
  { value: "Surat Keluar", label: "Surat Keluar" },
  { value: "Keputusan", label: "Keputusan" },
  { value: "Peraturan", label: "Peraturan" },
  { value: "Nota Dinas", label: "Nota Dinas" },
  { value: "Memo", label: "Memo" },
  { value: "Disposisi", label: "Disposisi" },
  { value: "Surat Perintah", label: "Surat Perintah" },
  { value: "Surat Tugas", label: "Surat Tugas" },
  { value: "Surat Perjalanan Dinas", label: "Surat Perjalanan Dinas" },
  { value: "Surat Edaran", label: "Surat Edaran" },
  { value: "Surat Kuasa", label: "Surat Kuasa" },
  { value: "Berita Acara", label: "Berita Acara" },
  { value: "Surat Keterangan", label: "Surat Keterangan" },
  { value: "Surat Pengantar", label: "Surat Pengantar" },
  { value: "Pengumuman", label: "Pengumuman" },
  { value: "Laporan", label: "Laporan" },
  { value: "Telaahan Staf", label: "Telaahan Staf" },
  { value: "Notula", label: "Notula" },
  { value: "Surat Undangan", label: "Surat Undangan" },
  { value: "Surat Izin", label: "Surat Izin" },
  { value: "Rekomendasi", label: "Rekomendasi" },
  { value: "Sertifikat", label: "Sertifikat" },
  { value: "Piagam", label: "Piagam" },
  { value: "Surat Perjanjian", label: "Surat Perjanjian" },
  { value: "SOP", label: "Standar Operasional Prosedur" },
  { value: "Lainnya", label: "Lainnya" },
] as const;

// Klasifikasi Keamanan sesuai Perwako 31/2023
export const KLASIFIKASI_KEAMANAN = [
  { value: "B", label: "Biasa/Terbuka", color: "bg-green-100 text-green-800 border-green-200" },
  { value: "T", label: "Terbatas", color: "bg-yellow-100 text-yellow-800 border-yellow-200" },
  { value: "R", label: "Rahasia", color: "bg-orange-100 text-orange-800 border-orange-200" },
  { value: "SR", label: "Sangat Rahasia", color: "bg-red-100 text-red-800 border-red-200" },
] as const;

// Retensi Arsip sesuai Perwako 11/2025
export const KETERANGAN_RETENSI = [
  { value: "Musnah", label: "Musnah", color: "bg-slate-100 text-slate-800" },
  { value: "Permanen", label: "Permanen", color: "bg-blue-100 text-blue-800" },
] as const;

export const STATUS_ARSIP = [
  { value: "Aktif", label: "Aktif", color: "bg-emerald-100 text-emerald-800" },
  { value: "Inaktif", label: "Inaktif", color: "bg-amber-100 text-amber-800" },
] as const;
